services:

  db_product:
      image: postgres:16.3
      env_file:
        - .env
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - network_product
      restart: unless-stopped

  node_product:
    build: .
    container_name: node_product
    volumes:
      - .:/usr/src/product
    ports:
      - "3000:3000"
    networks:
      - network_product
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_product:5432/${POSTGRES_DB}"
    restart: unless-stopped
    depends_on:
      - db_product

networks:
  network_product:

volumes:
  postgres_data:
  